import { NextResponse } from 'next/server'
import { z } from 'zod'
import { auth } from '@/lib/auth'
import { db } from '@/lib/db'
import { decrypt } from '@/lib/crypto'
import { createRepo, pushFiles } from '@/lib/github'

const schema = z.object({
  projectId: z.string(),
  repoName: z.string().min(1).max(80).optional(),
  private: z.boolean().optional(),
})

export async function POST(req: Request) {
  const session = await auth()
  if (!session?.user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  const userId = (session.user as any).id

  const body = await req.json().catch(() => null)
  const parsed = schema.safeParse(body)
  if (!parsed.success) return NextResponse.json({ error: 'Invalid input' }, { status: 400 })
  const { projectId, repoName, private: isPrivate = false } = parsed.data

  // Load project + user's GitHub PAT
  const [project, ghToken] = await Promise.all([
    db.project.findUnique({ where: { id: projectId }, include: { files: true } }),
    db.githubToken.findUnique({ where: { userId } }),
  ])
  if (!project) return NextResponse.json({ error: 'Project not found' }, { status: 404 })
  if (project.userId !== userId) return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
  if (!ghToken) return NextResponse.json({ error: 'Connect your GitHub account first' }, { status: 400 })
  if (project.files.length === 0) return NextResponse.json({ error: 'Generate files first' }, { status: 400 })

  const pat = decrypt(ghToken.encryptedPat)
  const name = repoName || project.slug

  await db.project.update({ where: { id: projectId }, data: { status: 'PUSHING' } })

  try {
    // 1. Create repo
    const repo = await createRepo(pat, {
      name,
      description: project.description ?? `Generated by Pullarao 1: ${project.name}`,
      private: isPrivate,
      autoInit: true,
    })

    // 2. Push all files
    const files = project.files.map(f => ({ path: f.path, content: f.content, message: `feat: add ${f.path}` }))
    const result = await pushFiles(pat, ghToken.githubLogin!, repo.name, repo.defaultBranch, files)

    // 3. Trigger Actions (workflow runs on push automatically if .github/workflows exists)
    await db.project.update({
      where: { id: projectId },
      data: {
        status: 'PUSHED',
        githubRepoOwner: ghToken.githubLogin,
        githubRepoName: repo.name,
        githubRepoUrl: repo.htmlUrl,
      },
    })

    return NextResponse.json({
      ok: true,
      repoUrl: repo.htmlUrl,
      pushed: result.pushed,
      failed: result.failed,
      message: result.failed.length
        ? `Pushed ${result.pushed} files, ${result.failed.length} failed`
        : `Pushed ${result.pushed} files to ${repo.fullName}`,
    })
  } catch (e: any) {
    await db.project.update({ where: { id: projectId }, data: { status: 'FAILED' } })
    return NextResponse.json({ error: e.message }, { status: 500 })
  }
}
